color_scheme:
  colors:
  - {color: '#3CD9ED', name: Primary}
  - {color: '#004F57', name: Primary Container}
  - {color: '#00363D', name: On Primary}
  - {color: '#96F0FF', name: On Primary Container}
  - {color: '#B1CBD0', name: Secondary}
  - {color: '#334B4F', name: Secondary Container}
  - {color: '#1C3438', name: On Secondary}
  - {color: '#CDE7EC', name: On Secondary Container}
  - {color: '#BAC6EA', name: Tertiary}
  - {color: '#3B4664', name: Tertiary Container}
  - {color: '#24304D', name: On Tertiary}
  - {color: '##DAE2FF', name: On Tertiary Container}
  - {color: '#FFB4AB', name: Error}
  - {color: '#101415', name: Background}
  - {color: '#101415', name: Surface}
  - {color: '#E1E3E3', name: On Background}
  - {color: '#C4C7C7', name: On Surface}
  - {color: '#3F484A', name: Surface Variant}
  - {color: '#BFC8CA', name: On Surface Variant}
  - {color: '#899294', name: Outline}
  - {color: 'rgba(203, 232, 237, 0.08)', name: Dark Overlay 1}
  - {color: 'rgba(203, 232, 237, 0.12)', name: Dark Overlay 2}
  - {color: 'rgba(203, 232, 237, 0.08)', name: Light Overlay 1}
  - {color: 'rgba(203, 232, 237, 0.12)', name: Light Overlay 2}
  - {color: 'rgba(225, 227, 227, 0.12)', name: Disabled Container}
  - {color: 'rgba(225, 227, 227, 0.38)', name: On Disabled}
  - {color: 'rgba(60, 217, 237, 0.05)', name: Primary Overlay 1}
  - {color: 'rgba(60, 217, 237, 0.08)', name: Primary Overlay 2}
  - {color: 'rgba(60, 217, 237, 0.11)', name: Primary Overlay 3}
  - {color: '#3F484A', name: Outline Variant}
  - {color: '#690005', name: On Error}
  - {color: '#191C1D', name: Surface Container Low}
  - {color: '#252B2C', name: Surface Container High}
  - {color: '#323536', name: Surface Container Highest}
  - {color: 'rgba(225, 227, 227, 0.04)', name: Disabled Container 2}
  - {color: 'rgba(255, 180, 171, 0.08)', name: Error Overlay 1}
  - {color: 'rgba(255, 180, 171, 0.12)', name: Error Overlay 2}
  - {color: 'rgba(203, 232, 237, 0.16)', name: Dark Overlay 3}
  - {color: '#FFDAD6', name: On Error Container}
  - {color: '#1D2021', name: Surface Container}
  - {color: '#E1E3E3', name: Inverse Surface}
  - {color: '#191C1D', name: Inverse On Surface}
  - {color: 'rgba(191,200,202, 0.08)', name: On Surface Variant Overlay 1}
  - {color: 'rgba(191,200,202, 0.12)', name: On Surface Variant Overlay 2}
  - {color: 'rgba(25,28,29, 0.08)', name: Inverse On Surface Overlay 1}
  - {color: 'rgba(25,28,29, 0.12)', name: Inverse On Surface Overlay 2}
  preset_groups: []
roles: []
